Repository MarcinJakobik/Web-And-API-Testing-Project, pull requests merged in 2023-04, with the labels that each got.

#1 Initial Push
  .idea/.gitignore
  .idea/compiler.xml
  .idea/dbnavigator.xml
  .idea/encodings.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/vcs.xml
  pom.xml
  src/main/java/com/sparta/badgerBytes/App.java
  src/main/resources/log4j2.properties
  src/test/java/com/sparta/badgerBytes/AppTest.java
Labels: documentation, enhancement

#15 Injector, DTOs, & Major Refactoring
  .idea/compiler.xml
  .idea/dbnavigator.xml
  .idea/libraries/Maven__com_fasterxml_jackson_core_jackson_annotations_2_14_2.xml
  .idea/libraries/Maven__com_fasterxml_jackson_core_jackson_core_2_14_2.xml
  .idea/libraries/Maven__com_fasterxml_jackson_core_jackson_databind_2_14_2.xml
  .idea/libraries/Maven__commons_codec_commons_codec_1_11.xml
  .idea/libraries/Maven__commons_logging_commons_logging_1_2.xml
  .idea/libraries/Maven__io_rest_assured_json_path_5_3_0.xml
  .idea/libraries/Maven__io_rest_assured_rest_assured_5_3_0.xml
  .idea/libraries/Maven__io_rest_assured_rest_assured_common_5_3_0.xml
  .idea/libraries/Maven__io_rest_assured_xml_path_5_3_0.xml
  .idea/libraries/Maven__net_bytebuddy_byte_buddy_1_12_21.xml
  .idea/libraries/Maven__org_apache_commons_commons_lang3_3_11.xml
  .idea/libraries/Maven__org_apache_groovy_groovy_4_0_6.xml
  .idea/libraries/Maven__org_apache_groovy_groovy_json_4_0_6.xml
  .idea/libraries/Maven__org_apache_groovy_groovy_xml_4_0_6.xml
  .idea/libraries/Maven__org_apache_httpcomponents_httpclient_4_5_13.xml
  .idea/libraries/Maven__org_apache_httpcomponents_httpcore_4_4_13.xml
  .idea/libraries/Maven__org_apache_httpcomponents_httpmime_4_5_13.xml
  .idea/libraries/Maven__org_apache_logging_log4j_log4j_api_2_20_0.xml
  .idea/libraries/Maven__org_apache_logging_log4j_log4j_core_2_20_0.xml
  .idea/libraries/Maven__org_apiguardian_apiguardian_api_1_1_2.xml
  .idea/libraries/Maven__org_assertj_assertj_core_3_24_2.xml
  .idea/libraries/Maven__org_ccil_cowan_tagsoup_tagsoup_1_2_1.xml
  .idea/libraries/Maven__org_hamcrest_hamcrest_2_1.xml
  .idea/libraries/Maven__org_junit_jupiter_junit_jupiter_5_9_2.xml
  .idea/libraries/Maven__org_junit_jupiter_junit_jupiter_api_5_9_2.xml
  .idea/libraries/Maven__org_junit_jupiter_junit_jupiter_engine_5_9_2.xml
  .idea/libraries/Maven__org_junit_jupiter_junit_jupiter_params_5_9_2.xml
  .idea/libraries/Maven__org_junit_platform_junit_platform_commons_1_9_2.xml
  .idea/libraries/Maven__org_junit_platform_junit_platform_engine_1_9_2.xml
  .idea/libraries/Maven__org_opentest4j_opentest4j_1_2_0.xml
  .idea/modules.xml
  src/test/java/com/sparta/badgerBytes/AppTest.java
  src/test/java/com/sparta/badgerBytes/testFramework/controll/ConnectionManager.java
  src/test/java/com/sparta/badgerBytes/testFramework/model/Injector.java
  src/test/java/com/sparta/badgerBytes/testFramework/model/ToJson.java
  src/test/java/com/sparta/badgerBytes/testFramework/model/dto/BrandListDTO.java
  src/test/java/com/sparta/badgerBytes/testFramework/model/dto/ProductListDTO.java
  src/test/java/com/sparta/badgerBytes/testFramework/model/dto/SuperDTO.java
  src/test/java/com/sparta/badgerBytes/testFramework/model/dto/UserAccountDTO.java
  src/test/java/com/sparta/badgerBytes/testFramework/model/dto/UserCredentialsDTO.java
  src/test/java/com/sparta/badgerBytes/tests/InjectorTests.java
  target/classes/log4j2.properties
  webAndApiAutomationProject.iml
Labels: documentation, enhancement

#16 Test Setup Files
  src/test/java/com/sparta/badgerBytes/tests/BrandListDTOTests.java
  src/test/java/com/sparta/badgerBytes/tests/ConnectionManagerTests.java
  src/test/java/com/sparta/badgerBytes/tests/ProductListDTOTests.java
  src/test/java/com/sparta/badgerBytes/tests/UserAccountDTOTests.java
  src/test/java/com/sparta/badgerBytes/tests/UserCredentialsDTOTests.java
Labels: enhancement

#19 Reg & Usman BrandsList Updates
  src/test/java/com/sparta/badgerBytes/testFramework/model/dto/BrandsListDTO.java
  src/test/java/com/sparta/badgerBytes/tests/BrandListDTOTests.java
  src/test/java/com/sparta/badgerBytes/tests/BrandsListDTOTests.java
  src/test/java/com/sparta/badgerBytes/tests/InjectorTests.java
Labels: enhancement

#25 product list DTO changes
  src/test/java/com/sparta/badgerBytes/tests/ProductListDTOTests.java
Labels: enhancement

#35 Reg logger
  src/main/resources/log4j2.properties
  src/test/java/com/sparta/badgerBytes/tests/BrandsListDTOTests.java
  src/test/java/com/sparta/badgerBytes/tests/UserCredentialsDTOTests.java
  target/classes/log4j2.properties
Labels: enhancement

#51 Reg Merge Updates
  src/test/java/com/sparta/badgerBytes/webTesting/cucumber/TestRunner.java
  src/test/java/com/sparta/badgerBytes/webTesting/cucumber/stepdefs/BackgroundStepdefs.java
  src/test/java/com/sparta/badgerBytes/webTesting/cucumber/stepdefs/BrandNavigationStepDef.java
  src/test/java/com/sparta/badgerBytes/webTesting/cucumber/stepdefs/ContactUsFormStepDefs.java
  src/test/java/com/sparta/badgerBytes/webTesting/cucumber/stepdefs/MyStepdefs.java
  src/test/java/com/sparta/badgerBytes/webTesting/cucumber/stepdefs/RegisterUserWithExistingEmailStepdefs.java
  src/test/java/com/sparta/badgerBytes/webTesting/cucumber/stepdefs/StepDefNavigateToTestCasesPage.java
  src/test/java/com/sparta/badgerBytes/webTesting/cucumber/stepdefs/StepDefPlaceOrder.java
  src/test/java/com/sparta/badgerBytes/webTesting/pom/pages/Cart.java
  src/test/java/com/sparta/badgerBytes/webTesting/pom/pages/ContactUs.java
  src/test/java/com/sparta/badgerBytes/webTesting/pom/pages/ContactUsPage.java
  src/test/java/com/sparta/badgerBytes/webTesting/pom/pages/HomePage.java
  src/test/java/com/sparta/badgerBytes/webTesting/pom/pages/SignupLoginPage.java
  src/test/resources/Archibald.png
  src/test/resources/features/BrandProductsSideBarNav.feature
  src/test/resources/features/backgrounds.feature
  src/test/resources/features/contactUsForm.feature
  src/test/resources/features/loginWithIncorrectDetails.feature
  src/test/resources/features/navigateToTestCasesPage.feature
  src/test/resources/features/registerUserWithExistingEmail.feature
  src/test/resources/features/websiteNavigation.feature
Labels: documentation, enhancement

#59 Hopefully Final Driver Update
  src/test/java/com/sparta/badgerBytes/apiTesting/tests/ProductListDTOTests.java
  src/test/java/com/sparta/badgerBytes/webTesting/cucumber/TestRunner.java
  src/test/java/com/sparta/badgerBytes/webTesting/cucumber/stepdefs/BackgroundStepdefs.java
  src/test/java/com/sparta/badgerBytes/webTesting/cucumber/stepdefs/BrandNavigationStepDef.java
  src/test/java/com/sparta/badgerBytes/webTesting/cucumber/stepdefs/CartMailSubscriptionStepDefs.java
  src/test/java/com/sparta/badgerBytes/webTesting/cucumber/stepdefs/ContactUs/ContactUs.java
  src/test/java/com/sparta/badgerBytes/webTesting/cucumber/stepdefs/HomeMailSubscriptionStepDefs.java
  src/test/java/com/sparta/badgerBytes/webTesting/cucumber/stepdefs/ProductsStepDefs.java
  src/test/java/com/sparta/badgerBytes/webTesting/cucumber/stepdefs/StepDefPlaceOrder.java
  src/test/java/com/sparta/badgerBytes/webTesting/cucumber/stepdefs/StepDefRemoveProductsFromCart.java
  src/test/java/com/sparta/badgerBytes/webTesting/cucumber/stepdefs/UserAlreadyRegistered/UserAlreadyRegistered.java
  src/test/java/com/sparta/badgerBytes/webTesting/cucumber/stepdefs/registerusersteps/RegisterUsersteps.java
  src/test/java/com/sparta/badgerBytes/webTesting/pom/pages/CartPage.java
  src/test/java/com/sparta/badgerBytes/webTesting/pom/pages/CheckoutPage.java
  src/test/java/com/sparta/badgerBytes/webTesting/pom/pages/HomePage.java
  src/test/java/com/sparta/badgerBytes/webTesting/pom/pages/ProductDetailsPage.java
  src/test/java/com/sparta/badgerBytes/webTesting/pom/pages/ProductsPage.java
  src/test/java/com/sparta/badgerBytes/webTesting/pom/pages/SuperFooterPage.java
  src/test/resources/features/ContactUs.feature
  src/test/resources/features/RemoveProductsFromCart.feature
  src/test/resources/features/UserAlreadyRegistered.feature
  src/test/resources/features/products.feature
  src/test/resources/features/registerUser.feature
  src/test/resources/webTesting.properties
Labels: documentation, enhancement

#63 Updated Readme with Web Testing (Sprint 2)
  README.md
Labels: documentation

#70 Driver Merge
  src/test/java/com/sparta/badgerBytes/webTesting/cucumber/stepdefs/BackgroundStepdefs.java
  src/test/java/com/sparta/badgerBytes/webTesting/cucumber/stepdefs/BrandNavigationStepDef.java
  src/test/java/com/sparta/badgerBytes/webTesting/cucumber/stepdefs/CartMailSubscriptionStepDefs.java
  src/test/java/com/sparta/badgerBytes/webTesting/cucumber/stepdefs/ContactUs.java
  src/test/java/com/sparta/badgerBytes/webTesting/cucumber/stepdefs/ContactUsFormStepDefs.java
  src/test/java/com/sparta/badgerBytes/webTesting/cucumber/stepdefs/HomeMailSubscriptionStepDefs.java
  src/test/java/com/sparta/badgerBytes/webTesting/cucumber/stepdefs/InvalidLoginDetails.java
  src/test/java/com/sparta/badgerBytes/webTesting/cucumber/stepdefs/LoginWithCorrectDetails.java
  src/test/java/com/sparta/badgerBytes/webTesting/cucumber/stepdefs/ProductsStepDefs.java
  src/test/java/com/sparta/badgerBytes/webTesting/cucumber/stepdefs/RegisterUserWithExistingEmailStepdefs.java
  src/test/java/com/sparta/badgerBytes/webTesting/cucumber/stepdefs/RegisterUsersteps.java
  src/test/java/com/sparta/badgerBytes/webTesting/cucumber/stepdefs/StepDefNavigateToTestCasesPage.java
  src/test/java/com/sparta/badgerBytes/webTesting/cucumber/stepdefs/StepDefPlaceOrder.java
  src/test/java/com/sparta/badgerBytes/webTesting/cucumber/stepdefs/StepDefRemoveProductsFromCart.java
  src/test/java/com/sparta/badgerBytes/webTesting/cucumber/stepdefs/StepDefsProductsInCart.java
  src/test/java/com/sparta/badgerBytes/webTesting/cucumber/stepdefs/SuccessfulLogoutStepDefs.java
  src/test/java/com/sparta/badgerBytes/webTesting/cucumber/stepdefs/UserAlreadyRegistered.java
Labels: enhancement

#72 FINISHED!!!!!!
  .gitignore
  src/test/java/com/sparta/badgerBytes/webTesting/cucumber/stepdefs/ContactUsFormStepDefs.java
  src/test/java/com/sparta/badgerBytes/webTesting/cucumber/stepdefs/RegisterUserWithExistingEmailStepdefs.java
  src/test/java/com/sparta/badgerBytes/webTesting/pom/pages/SignupLoginPage.java
Labels: enhancement

#76 Current Merge of files in progress
  src/test/java/com/sparta/badgerBytes/webTesting/cucumber/stepdefs/BackgroundStepdefs.java
  src/test/java/com/sparta/badgerBytes/webTesting/cucumber/stepdefs/RegisterUserWithExistingEmailStepdefs.java
  src/test/java/com/sparta/badgerBytes/webTesting/pom/pages/SignupLoginPage.java
Labels: enhancement

#79 Final adjustments to TC 5
  src/test/java/com/sparta/badgerBytes/webTesting/cucumber/stepdefs/BackgroundStepdefs.java
  src/test/java/com/sparta/badgerBytes/webTesting/cucumber/stepdefs/RegisterUserWithExistingEmailStepdefs.java
  src/test/java/com/sparta/badgerBytes/webTesting/pom/pages/SignupLoginPage.java
Labels: enhancement

#82 Liam's Fixes
  src/test/java/com/sparta/badgerBytes/webTesting/cucumber/stepdefs/StepDefPlaceOrder.java
  src/test/resources/features/PlaceOrders.feature
  src/test/resources/webTesting.properties
Labels: enhancement

#84 Onur's Test Fix
  src/test/resources/features/UserAlreadyRegistered.feature
  src/test/resources/webTesting.properties
Labels: enhancement

#86 Fixed most of the remaining errors
  src/test/java/com/sparta/badgerBytes/webTesting/cucumber/stepdefs/CartMailSubscriptionStepDefs.java
  src/test/java/com/sparta/badgerBytes/webTesting/cucumber/stepdefs/HomeMailSubscriptionStepDefs.java
  src/test/java/com/sparta/badgerBytes/webTesting/cucumber/stepdefs/ProductsStepDefs.java
  src/test/java/com/sparta/badgerBytes/webTesting/cucumber/stepdefs/UserAlreadyRegistered.java
Labels: enhancement

#87 Update README.md
  README.md
Labels: documentation
